# Sets

* Sets are mutable ,unordered collection of items enclosed parentesis followed by flower brackets
* The elements of Sets are also seperated by comma | Each element in a set is unique and immutable
* Datatypes stored in set are immutable i.e., Tuples and strings

## Contents
  ##### 1.Creating an empty Set
  ##### 2.Creating a Set with elements
  ##### 3.Accessing /Traversing the Set
  ##### 4.Update/Insert a Set in python
  ##### 5.Slicing  Concept in Set
  ##### 6.Deletion methods in Set
---

### 1.Creating an empty Set

In [8]:
# with the help of set()
empty_Set=set()
print(type(empty_Set))

<class 'set'>

In [16]:
sety=({1.})
print(type(sety))

<class 'set'>

### 2.Creating a Set with elements

In [19]:
ing=({1,2,3,4,5,6,7})
stg=({'ab','bc','cd'})
intstr= ({1,2,'ab',12.5})
print(type(ing))
print(type(stg))
print(type(intstr))

<class 'set'>
<class 'set'>
<class 'set'>



---

### 3.Accessing /Traversing the Set

* python set is a collection of unordered items
* It dosent follow any index order ,there will be no particular posistion for values to access them through the index

In [7]:
#Traversing -->visiting each element atleast once in the Set (traversing can be done using for loop)

#method 1 using membership operator in
nts= ({1,2,'ab',12.5})
for i in nts:
  print(i)

ab
1
2
12.5

âš¡Is it possible to loop towards an empty Set?

### 4.Update/Insert a Set in python
* Values inside a set are immutable data types hence they are not subscriptible
* we cannot update an element in the set
* but with different methods avaliable we can add elements to the set for example we can insert multiple values to the set using update() method in the set

In [12]:
# Updating elements --> without changing the memory location we update a value to a given location

Set1=({12,35,'hgf',13.65, 854})
Set1[5]= ({6})
Set1

TypeError: ignored

**Inserting elements in python Set (add(), update()**
 * add() --> to add single element in the set
 * update() --> to add multiple elements in the set

In [14]:
#1.Inserting/adding  single Element
# syntax =Set1.add({value)})

Set1=({12,35,'hgf',13.65, 854})
Set1.add('ab')
Set1

{12, 13.65, 35, 854, 'ab', 'hgf'}

In [15]:
# update method
Set1=({12,35,'hgf',13.65, 854})
Set1.update({'ccv','ccb1'})
Set1

{12, 13.65, 35, 854, 'ccb1', 'ccv', 'hgf'}


---

### 6.Deletion methods in Set

**Deletion of elements/Set can be done using discard() ,delete() clear()**

* Discard()-> removes an element from the set
* pop()--> removes arbitrary element in the Set
* clear()  -> removes all elements from the set
* del      -> deletes the entire set

In [17]:
#Discard()-> removes an element from the set
#syntax--> Set.discard(element)
Set1=({12,35,'hgf',13.65, 854})
Set1.discard(35)
Set1

{12, 13.65, 854, 'hgf'}

In [19]:
#pop()--> removes arbitrary element in the Set
#syntax--> Set.pop()
Set1=({12,'hgf',13.65, 854})
Set1.pop()
Set1

{12, 13.65, 'hgf'}

In [20]:
# delete method works on entire set
#syntax--> del Set({index})
Set1=({12,35,'hgf',13.65, 854})
del Set1
Set1

NameError: ignored

In [22]:
#clear method (be removes the entire set elements and throws an empty set )
#syntax--> Set.clear()

Set1=({12,35,'hgf',13.65, 854})
Set1.clear()
Set1

set()

In [21]:
#Remove method (throws an error if element dosentexist in the set hence discard is used)
#syntax--> Set.remove('element') #it does not take more than one argument

Set1=({12,35,'hgf',13.65, 854})
Set1.remove(852)
Set1

KeyError: ignored

In [23]:
##Searching an elemnet in the Set
#1)Using in operator

Set1=({12,35,'hgf',13.65, 854})
target= 13.65
if target in Set1:
  print(f"{target} is in the Set")
else:
  print(f"{target} is not in the Set")

13.65 is in the Set

In [24]:
#2)Using linear search
Set1=({12,35,'hgf',13.65, 854})
def linearsearch(Set1 ,target):
  for i , value in enumerate(Set1):   # i takes index,value takes element
      if  value == target:
        return i
  return -1
print(linearsearch(Set1,854))

2


---

### Set Operations/functions

* Union() appends two sets

In [26]:
# union()-> appens two sets

a=({1,2,3})
b=({4,7,9})
a.union(b)

{1, 2, 3, 4, 7, 9}

In [27]:
# Intersection --> view object that shows common elements in 2 sets
a=({1,2,3,4, 6 ,9})
b=({4,7,9})
a.intersection(b)

{4, 9}

In [29]:
# Set difference
# a-b - elements that are present in a but not in b |(also written as a.difference(b))
a=({1,2,3,4, 6 ,9})
b=({4,7,9})
print(a-b)
print(b.difference(a))

{1, 2, 3, 6}
{7}

In [30]:
# Symmetric difference [Union-Intersection]
a=({1,2,3,4, 6 ,9})
b=({4,7,9})
print(a ^ b)
print(a.symmetric_difference(b))

{1, 2, 3, 6, 7}
{1, 2, 3, 6, 7}